// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Repositories;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220717152121_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Web.Entities.Gift", b =>
                {
                    b.Property<string>("GiftCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("GiftCode");

                    b.ToTable("Gift");
                });

            modelBuilder.Entity("Web.Entities.Prize", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Duration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StudentId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Prize");
                });

            modelBuilder.Entity("Web.Entities.PrizeItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GiftCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PrizeId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ScholarshipCode")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GiftCode");

                    b.HasIndex("PrizeId");

                    b.HasIndex("ScholarshipCode");

                    b.ToTable("PrizeItem");
                });

            modelBuilder.Entity("Web.Entities.Scholarship", b =>
                {
                    b.Property<string>("ScholarshipCode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("ScholarshipType")
                        .HasColumnType("int");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ScholarshipCode");

                    b.ToTable("Scholarship");
                });

            modelBuilder.Entity("Web.Entities.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Web.Entities.Prize", b =>
                {
                    b.HasOne("Web.Entities.Student", "Student")
                        .WithMany("Prizes")
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Web.Entities.PrizeItem", b =>
                {
                    b.HasOne("Web.Entities.Gift", "Gift")
                        .WithMany()
                        .HasForeignKey("GiftCode");

                    b.HasOne("Web.Entities.Prize", "Prize")
                        .WithMany("PrizeItems")
                        .HasForeignKey("PrizeId");

                    b.HasOne("Web.Entities.Scholarship", "Scholarship")
                        .WithMany()
                        .HasForeignKey("ScholarshipCode");

                    b.Navigation("Gift");

                    b.Navigation("Prize");

                    b.Navigation("Scholarship");
                });

            modelBuilder.Entity("Web.Entities.Prize", b =>
                {
                    b.Navigation("PrizeItems");
                });

            modelBuilder.Entity("Web.Entities.Student", b =>
                {
                    b.Navigation("Prizes");
                });
#pragma warning restore 612, 618
        }
    }
}
